// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjekatVeb2.Data;

#nullable disable

namespace ProjekatVeb2.Migrations
{
    [DbContext(typeof(ContextDB))]
    partial class ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjekatVeb2.Models.Administrator", b =>
                {
                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KorisnickoIme");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Administratori");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.Artikal", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdavacID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Slika")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProdavacID");

                    b.ToTable("Artikal");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.Kupac", b =>
                {
                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusPorudzbine")
                        .HasColumnType("int");

                    b.HasKey("KorisnickoIme");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Kupac");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.Porudzbina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresaDostave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtikalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Kolicina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KupacID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProdavacKorisnickoIme")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("UkupnaCijena")
                        .HasColumnType("real");

                    b.Property<DateTime>("VrijemeDostave")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VrijemePorudzbine")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArtikalId");

                    b.HasIndex("KupacID");

                    b.HasIndex("ProdavacKorisnickoIme");

                    b.ToTable("Porudzbina");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.PoruzdbinaArtikal", b =>
                {
                    b.Property<string>("IdPorudzbina")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArtikalID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cijena")
                        .HasColumnType("int");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("PorudzbinaId")
                        .HasColumnType("int");

                    b.HasKey("IdPorudzbina", "ArtikalID");

                    b.HasIndex("ArtikalID");

                    b.HasIndex("PorudzbinaId");

                    b.ToTable("PoruzdbinaArtikli");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.Prodavac", b =>
                {
                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdministratorKorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusPorudzbine")
                        .HasColumnType("int");

                    b.Property<int>("Verifikovan")
                        .HasColumnType("int");

                    b.HasKey("KorisnickoIme");

                    b.HasIndex("AdministratorKorisnickoIme");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Prodavci");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.Artikal", b =>
                {
                    b.HasOne("ProjekatVeb2.Models.Prodavac", "Prodavac")
                        .WithMany("Artikli")
                        .HasForeignKey("ProdavacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodavac");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.Kupac", b =>
                {
                    b.HasOne("ProjekatVeb2.Models.Administrator", "Administrator")
                        .WithMany("Kupci")
                        .HasForeignKey("KorisnickoIme")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.Porudzbina", b =>
                {
                    b.HasOne("ProjekatVeb2.Models.Artikal", "Artikal")
                        .WithMany()
                        .HasForeignKey("ArtikalId");

                    b.HasOne("ProjekatVeb2.Models.Kupac", "Kupac")
                        .WithMany("Porudzbina")
                        .HasForeignKey("KupacID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjekatVeb2.Models.Prodavac", null)
                        .WithMany("Poruzbine")
                        .HasForeignKey("ProdavacKorisnickoIme");

                    b.Navigation("Artikal");

                    b.Navigation("Kupac");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.PoruzdbinaArtikal", b =>
                {
                    b.HasOne("ProjekatVeb2.Models.Artikal", "Artikal")
                        .WithMany("PoruceniArtikli")
                        .HasForeignKey("ArtikalID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjekatVeb2.Models.Porudzbina", "Porudzbina")
                        .WithMany("PoruceniArtikli")
                        .HasForeignKey("PorudzbinaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Porudzbina");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.Prodavac", b =>
                {
                    b.HasOne("ProjekatVeb2.Models.Administrator", "Administrator")
                        .WithMany("Prodavci")
                        .HasForeignKey("AdministratorKorisnickoIme")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.Administrator", b =>
                {
                    b.Navigation("Kupci");

                    b.Navigation("Prodavci");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.Artikal", b =>
                {
                    b.Navigation("PoruceniArtikli");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.Kupac", b =>
                {
                    b.Navigation("Porudzbina");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.Porudzbina", b =>
                {
                    b.Navigation("PoruceniArtikli");
                });

            modelBuilder.Entity("ProjekatVeb2.Models.Prodavac", b =>
                {
                    b.Navigation("Artikli");

                    b.Navigation("Poruzbine");
                });
#pragma warning restore 612, 618
        }
    }
}
